android: PLATFORM=android -r features/android/support -r features/android -r features/step_definitions -r features/android/pages


ios: PLATFORM=ios -r features/ios/support -r features/step_definitions -r features/ios/pages
